exclude: "docs|notebooks|node_modules|.vscode|.venv|.git|.tox|.pytest_cache"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@commitlint/config-conventional"
        entry: commitlint --config config/common/commintlint.config.js --edit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args:
          [
            "--config-file",
            "pyproject.toml",
            "--python-executable",
            ".venv/bin/python",
          ]
        additional_dependencies: [django-stubs, types-all]
        files: ^todo_list/

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--settings-file", "pyproject.toml"]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        args:
          [
            "--rcfile",
            ".pylintrc",
          ]
