"""
Django settings for certainly_synapse_kb project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from typing import List

from .base import *  # pylint: disable=W0401,W0614

# https://docs.djangoproject.com/en/dev/ref/settings/#debug
DEBUG = True

SECRET_KEY = "#hcfe86ax6j1(s4!7bytvutw587+$we(**ex945@5j+0d=#2l="

ALLOWED_HOSTS: List[str] = ["localhost", "0.0.0.0", "127.0.0.1", ".ngrok.io"]  # type: ignore

# Application definition
# django-extensions
# ------------------------------------------------------------------------------
# https://django-extensions.readthedocs.io/en/latest/installation_instructions.html#configuration
INSTALLED_APPS += ["django_extensions"]  # noqa: F405
